export interface IconGallery {
    iconName: string
}

export const iconAllureFontData: IconGallery[] = [
    {iconName: "af-avepoint"},
    {iconName: "af-place-holder"},
    {iconName: "af-clipboard-remove"},
    {iconName: "af-clear-filter"},
    {iconName: "af-manage-column"},
    {iconName: "af-migration"},
    {iconName: "af-post-migration"},
    {iconName: "af-advanced-search"},
    {iconName: "af-eye"},
    {iconName: "af-rerun"},
    {iconName: "af-generate-report"},
    {iconName: "af-access"},
    {iconName: "af-delve"},
    {iconName: "af-excel"},
    {iconName: "af-exchange"},
    {iconName: "af-forms"},
    {iconName: "af-office"},
    {iconName: "af-onedrive"},
    {iconName: "af-onenote"},
    {iconName: "af-outlook"},
    {iconName: "af-power-bi"},
    {iconName: "af-powerpoint"},
    {iconName: "af-project"},
    {iconName: "af-sharepoint"},
    {iconName: "af-teams"},
    {iconName: "af-teams-personal-chat"},
    {iconName: "af-visio"},
    {iconName: "af-word"},
    {iconName: "af-yammer"},
    {iconName: "af-power-apps"},
    {iconName: "af-power-automate"},
    {iconName: "af-task"},
    {iconName: "af-contact"},
    {iconName: "af-journal"},
    {iconName: "af-filter"},
    {iconName: "af-grid"},
    {iconName: "af-compare"},
    {iconName: "af-folder-open-plus"},
    {iconName: "af-site-collection"},
    {iconName: "af-library"},
    {iconName: "af-planner"},
    {iconName: "af-channel"},
    {iconName: "af-file-earth"},
    {iconName: "af-data-management"},
    {iconName: "af-microsoft"},
    {iconName: "af-apple"},
    {iconName: "af-twitter"},
    {iconName: "af-facebook"},
    {iconName: "af-google"},
    {iconName: "af-environment"},
    {iconName: "af-power-platform"},
    {iconName: "af-salesforce-org"},
    {iconName: "af-icon-azure-storage"},
    {iconName: "af-icon-azure-virtual-machine"},
    {iconName: "af-icon-calling-management"},
    {iconName: "af-file-clock"},
    {iconName: "af-forum"},
    {iconName: "af-font-color"},
    {iconName: "af-icon-exchange-on-premises"},
    {iconName: "af-icon-full-governance"},
    {iconName: "af-unlink"},
    {iconName: "af-icon-admin-portal-settings"},
    {iconName: "af-unshare"},
    {iconName: "af-dollar-transfer"},
    {iconName: "af-squares"},
    {iconName: "af-rectangle-three-parts"},
    {iconName: "af-warning"},
    {iconName: "af-alphabet-a-pen"},
    {iconName: "af-approval"},
    {iconName: "af-bank-card"},
    {iconName: "af-medal-valuation"},
    {iconName: "af-pen-rating"},
    {iconName: "af-trend-rates"},
    {iconName: "af-desktop-arrow-trend-up"},
    {iconName: "af-trend-up"},
    {iconName: "af-hand-holding-card"},
    {iconName: "af-mail-enabled-security-group"},
    {iconName: "af-atlas"},
    {iconName: "af-cense"},
    {iconName: "af-cloud-archiving"},
    {iconName: "af-page"},
    {iconName: "af-cloud-index"},
    {iconName: "af-pulse"},
    {iconName: "af-amazon-ec2"},
    {iconName: "af-cloud-insights"},
    {iconName: "af-cloud-management"},
    {iconName: "af-cloud-records"},
    {iconName: "af-cloud-backup"},
    {iconName: "af-confide"},
    {iconName: "af-docave"},
    {iconName: "af-entrust"},
    {iconName: "af-file-share-navigator"},
    {iconName: "af-fly"},
    {iconName: "af-salesforce"},
    {iconName: "af-governance_automation"},
    {iconName: "af-group-hub"},
    {iconName: "af-office-connect"},
    {iconName: "af-perimeter"},
    {iconName: "af-pi"},
    {iconName: "af-recenter"},
    {iconName: "af-partially-finish"},
    {iconName: "af-ellipsis-vertical"},
]
export const iconFontAwesome: IconGallery[] = [
    {iconName: "far-address-book"},
    {iconName: "far-address-card"},
    {iconName: "far-bell"},
    {iconName: "far-bell-slash"},
    {iconName: "far-bookmark"},
    {iconName: "far-building"},
    {iconName: "far-calendar"},
    {iconName: "far-calendar-check"},
    {iconName: "far-calendar-days"},
    {iconName: "far-calendar-minus"},
    {iconName: "far-calendar-plus"},
    {iconName: "far-calendar-xmark"},
    {iconName: "far-chart-bar"},
    {iconName: "far-chess-bishop"},
    {iconName: "far-chess-king"},
    {iconName: "far-chess-king"},
    {iconName: "far-chess-knight"},
    {iconName: "far-chess-pawn"},
    {iconName: "far-chess-queen"},
    {iconName: "far-chess-rook"},
    {iconName: "far-circle"},
    {iconName: "far-circle-question"},
    {iconName: "far-circle-right"},
    {iconName: "far-circle-stop"},
    {iconName: "far-circle-up"},
    {iconName: "far-circle-user"},
    {iconName: "far-circle-xmark"},
    {iconName: "far-clipboard"},
    {iconName: "far-clock"},
    {iconName: "far-clone"},
    {iconName: "far-closed-captioning"},
    {iconName: "far-comment"},
    {iconName: "far-comment-dots"},
    {iconName: "far-comments"},
    {iconName: "far-compass"},
    {iconName: "far-copy"},
    {iconName: "far-copyright"},
    {iconName: "far-credit-card"},
    {iconName: "far-envelope"},
    {iconName: "far-envelope-open"},
    {iconName: "far-eye"},
    {iconName: "far-eye-slash"},
    {iconName: "far-face-angry"},
    {iconName: "far-face-dizzy" },
    {iconName: "far-face-flushed"},
    {iconName: "far-face-frown"},
    {iconName: "far-face-frown-open"},
    {iconName: "far-face-grimace"},
    {iconName: "far-face-grin"},
    {iconName: "far-face-grin-beam"},
    {iconName: "far-face-grin-beam-sweat" },
    {iconName: "far-face-grin-hearts"},
    {iconName: "far-face-grin-squint" },
    {iconName: "far-face-grin-squint-tears" },
    {iconName: "far-face-grin-stars" },
    {iconName: "far-face-grin-tears" },
    {iconName: "far-face-grin-tongue" },
    {iconName: "far-face-grin-tongue-squint" },
    {iconName: "far-face-grin-tongue-wink" },
    {iconName: "far-face-grin-wide" },
    {iconName: "far-face-grin-wink"  },
    {iconName: "far-face-kiss"  },
    {iconName: "far-face-kiss-beam"  },
    {iconName: "far-face-kiss-wink-heart" },
    {iconName: "far-face-laugh" },
    {iconName: "far-face-laugh-beam"  },
    {iconName: "far-face-laugh-squint" },
    {iconName: "far-face-laugh-wink" },
    {iconName: "far-face-meh" },
    {iconName: "far-face-meh-blank" },
    {iconName: "far-face-rolling-eyes" },
    {iconName: "far-face-sad-cry"  },
    {iconName: "far-face-sad-tear" },
    {iconName: "far-face-sad-tear"  },
    {iconName: "far-face-smile" },
    {iconName: "far-face-smile-beam"  },
    {iconName: "far-face-smile-wink"  },
    {iconName: "far-face-surprise" },
    {iconName: "far-face-tired" },
    {iconName: "far-file"  },
    {iconName: "far-file-audio" },
    {iconName: "far-file-code" },
    {iconName: "far-file-excel" },
    {iconName: "far-file-image"  },
    {iconName: "far-file-lines"  },
    {iconName: "far-file-pdf" },
    {iconName: "far-file-powerpoint" },
    {iconName: "far-file-video" },
    {iconName: "far-file-word" },
    {iconName: "far-file-zipper" },
    {iconName: "far-file-zipper" },
    {iconName: "far-file-excel" },
]
export const iconFontOffice: IconGallery[] = [
    {iconName: "12PointStar"},
    {iconName: "6PointStar"},
    {iconName: "AADLogo"},
    {iconName: "Accept" },
    {iconName: "AcceptMedium" },
    {iconName:"AccessibiltyChecker" },
    {iconName:"AccessLogo"},
    {iconName:"AccountActivity"},
    {iconName:"AccountBrowser"},
    {iconName:"AccountManagement"},
    {iconName:"Accounts"},
    {iconName:"ActionCenter"},
    {iconName:"ActivateOrders"},
    {iconName:"ActivityFeed"},
    {iconName:"Add"},
    {iconName:"AddBookmark"},
    {iconName:"AddConnection"},
    {iconName:"AddEvent"},
    {iconName:"AddFavorite"},
    {iconName:"AddFavoriteFill"},
    {iconName:"AddGroup"},
    {iconName:"AddHome"},
    {iconName:"AddIn"},
    {iconName:"AddOnlineMeeting"},
    {iconName:"AddReaction"},
    {iconName:"AddNotes"},
    {iconName:"AddPhone"},
]

